const header=document.querySelector('.site-header');
const progress=document.querySelector('.progress-bar');
const menuBtn=document.querySelector('.menu-btn');
const navLinks=document.querySelector('.nav-links');
menuBtn?.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');menuBtn.setAttribute('aria-expanded',open)});
navLinks?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>navLinks.classList.remove('open')));
function onScroll(){const y=window.scrollY;header?.classList.toggle('scrolled',y>30);const max=document.documentElement.scrollHeight-innerHeight;progress&&(progress.style.width=`${max?y/max*100:0}%`)}
addEventListener('scroll',onScroll,{passive:true});onScroll();
const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');if(e.target.matches('.metric-row,.dashboard-shell'))animateCounts(e.target);io.unobserve(e.target)}}),{threshold:.14});
document.querySelectorAll('.reveal,.workflow-card,.metric-row,.dashboard-shell').forEach(el=>io.observe(el));
let counted=false;function animateCounts(root){if(counted)return;counted=true;document.querySelectorAll('[data-count]').forEach(el=>{const target=Number(el.dataset.count),suffix=el.dataset.suffix||'';const start=performance.now(),duration=1200;function tick(now){const p=Math.min((now-start)/duration,1),ease=1-Math.pow(1-p,3);el.textContent=`${Math.round(target*ease)}${suffix}`;if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)})}
const roleContent={
secretary:{eyebrow:'Secretary workspace',title:'From meeting preparation to structured draft minutes.',text:'CORE gathers committee reports, carries unfinished business forward, records motions and decisions, creates follow-up tasks and prepares the meeting record for review.',items:['Agenda preparation','Report readiness','Motions & decisions','Draft minutes']},
president:{eyebrow:'President & board workspace',title:'See the entire organization before the meeting begins.',text:'CORE shows what is ready, what is stalled, what needs a decision and which responsibilities require intervention.',items:['Board readiness','Committee oversight','Pending approvals','Decision follow-up']},
treasurer:{eyebrow:'Treasurer workspace',title:'Keep financial decisions connected to the records behind them.',text:'Reports, approvals, supporting evidence and resulting actions remain attached to the governance process that authorized them.',items:['Financial reports','Approval records','Evidence links','Continuity archive']},
bylaw:{eyebrow:'By-Law Officer workspace',title:'Turn each comparison into assigned, resolvable work.',text:'Potential issues connect to the relevant article, governing authority, committee task list, review stage, evidence and final resolution.',items:['Annual comparison','Article review','Legal-review status','Amendment history']},
committee:{eyebrow:'Committee Chair workspace',title:'A mandate becomes an operating workspace.',text:'Projects, owners, evidence, deadlines and reports remain visible to the committee and ready for the next board meeting.',items:['Mandate dashboard','Projects & tasks','Evidence collection','Meeting reports']},
director:{eyebrow:'Board Member workspace',title:'Arrive prepared with the decisions and records already connected.',text:'Review agenda materials, supporting evidence, unresolved items and prior decisions without searching through scattered folders.',items:['Meeting package','Decision context','Supporting records','Assigned follow-ups']}
};
const panel=document.querySelector('#role-panel');document.querySelectorAll('.role-tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.role-tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const d=roleContent[btn.dataset.role];panel.classList.add('switching');setTimeout(()=>{panel.innerHTML=`<span class="eyebrow">${d.eyebrow}</span><h3>${d.title}</h3><p>${d.text}</p><div class="role-benefits">${d.items.map(x=>`<span>${x}</span>`).join('')}</div>`;panel.classList.remove('switching')},180)}));
const magnets=document.querySelectorAll('.magnetic');magnets.forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.08}px,${(e.clientY-r.top-r.height/2)*.12}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});
const form=document.querySelector('#demo-form');form?.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(form);const subject=encodeURIComponent(`StoneCarta demonstration request — ${data.get('organization')||'Organization'}`);const body=encodeURIComponent(`Name: ${data.get('name')}\nEmail: ${data.get('email')}\nOrganization: ${data.get('organization')}\nRole: ${data.get('role')}\nJurisdiction: ${data.get('jurisdiction')}\n\nPrimary challenge:\n${data.get('challenge')}`);document.querySelector('.success').style.display='block';window.location.href=`mailto:demo@stonecarta.com?subject=${subject}&body=${body}`});
