const menuBtn=document.querySelector('.menu-btn');const navLinks=document.querySelector('.nav-links');
menuBtn?.addEventListener('click',()=>navLinks.classList.toggle('open'));
const roleContent={
 secretary:{title:'Meetings & Minutes',text:'CORE gathers committee reports, carries unfinished business forward, records motions and decisions, creates follow-up tasks and prepares structured draft minutes for review.',items:['Agenda preparation and distribution','Committee report readiness','Motions, decisions and follow-ups','Structured draft minutes']},
 president:{title:'President & Board Oversight',text:'See what is moving, what is stalled and what requires a decision before the board meets.',items:['Board-level readiness view','Agenda and approval oversight','Committee accountability','Decision and follow-up visibility']},
 treasurer:{title:'Treasurer & Corporate Records',text:'Keep financial reports, approvals, evidence and supporting documents connected to the decisions they support.',items:['Financial-report workflows','Approvals and evidence','Record continuity','Audit-ready exports']},
 bylaw:{title:'By-Law & Compliance Review',text:'Turn each jurisdiction-specific comparison into assigned, trackable work with review stations and preserved evidence.',items:['Annual comparison workflow','Article-level review stations','Committee task lists','Resolution and amendment history']},
 committee:{title:'Committee Workspaces',text:'Give each committee a mandate-driven workspace for projects, assignments, deadlines, evidence and meeting reports.',items:['Mandate-based dashboards','Projects and tasks','Report preparation','Continuity between members']}
};
const panel=document.querySelector('#role-panel');document.querySelectorAll('.role-tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.role-tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const d=roleContent[btn.dataset.role];panel.innerHTML=`<span class="eyebrow">Your governance. Your role.</span><h3>${d.title}</h3><p>${d.text}</p><ul class="checklist">${d.items.map(x=>`<li>${x}</li>`).join('')}</ul>`;}));
const form=document.querySelector('#demo-form');form?.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(form);const subject=encodeURIComponent(`StoneCarta demonstration request — ${data.get('organization')||'Organization'}`);const body=encodeURIComponent(`Name: ${data.get('name')}\nEmail: ${data.get('email')}\nOrganization: ${data.get('organization')}\nRole: ${data.get('role')}\nJurisdiction: ${data.get('jurisdiction')}\n\nPrimary challenge:\n${data.get('challenge')}`);document.querySelector('.success').style.display='block';window.location.href=`mailto:demo@stonecarta.com?subject=${subject}&body=${body}`;});
