const seed=[
 {id:"bylaws",name:"By-Laws Committee",purpose:"Maintain and review the corporate by-laws and governance records.",chair:"Ryan Colclough",status:"on-track",progress:86,nextMeeting:"2026-07-29",members:[{name:"Ryan Colclough",role:"Chair"},{name:"Greg Forsyth",role:"Ex Officio"}],tasks:[{title:"Review Article VI",status:"in-progress",due:"2026-08-15"},{title:"Prepare ONCA comparison",status:"not-started",due:"2026-09-01"}],projects:[{name:"2026 By-Law Review",progress:64,status:"active"}]},
 {id:"finance",name:"Finance Committee",purpose:"Financial oversight, budgeting, insurance, and annual reporting.",chair:"Unassigned",status:"attention",progress:48,nextMeeting:"",members:[],tasks:[{title:"Confirm insurance renewal",status:"not-started",due:"2026-08-01"}],projects:[]},
 {id:"building",name:"Building Committee",purpose:"Building operations, maintenance, safety, and capital planning.",chair:"Unassigned",status:"setup",progress:20,nextMeeting:"",members:[],tasks:[],projects:[]}
];
export default function register(ctx){
 const {router,renderShell,storage,toast}=ctx,key="COMMITTEES";
 const get=()=>storage.get(key,seed),save=v=>storage.set(key,v);
 router.register("committees",()=>list());
 router.register("committee",params=>detail(params.id||"bylaws"));
 function list(){const items=get();renderShell(`<div class="backline"><button data-route="dashboard">‹ Dashboard</button></div><section class="hero"><div class="eyebrow">Operational Governance</div><h1>Committee Manager</h1><p>Manage mandates, members, responsibilities, projects, meetings, and records.</p><div class="rule"></div></section><section class="committee-toolbar"><button class="btn" type="button" data-new-committee>＋ Create Committee</button><div><strong>${items.length}</strong><span>Committees</span></div><div><strong>${items.reduce((s,c)=>s+c.tasks.filter(t=>t.status!=="complete").length,0)}</strong><span>Open Tasks</span></div></section><section class="committee-grid">${items.map(card).join("")}</section>`,"committees");}
 function card(c){return `<button class="committee-card glass-card" data-open-committee="${c.id}"><div class="committee-card-head"><span class="committee-status ${c.status}"></span><small>${label(c.status)}</small></div><h2>${esc(c.name)}</h2><p>${esc(c.purpose)}</p><div class="committee-progress"><span style="width:${c.progress}%"></span></div><div class="committee-stats"><div><b>${c.progress}%</b><small>Progress</small></div><div><b>${c.members.length}</b><small>Members</small></div><div><b>${c.tasks.filter(t=>t.status!=="complete").length}</b><small>Open Tasks</small></div></div><footer><span>Chair: ${esc(c.chair)}</span><b>Open →</b></footer></button>`}
 function detail(id){const c=get().find(x=>x.id===id);if(!c)return list();renderShell(`<div class="backline"><button data-route="committees">‹ All Committees</button></div><section class="committee-hero glass-card"><div><span>${label(c.status)}</span><h1>${esc(c.name)}</h1><p>${esc(c.purpose)}</p></div><div class="committee-ring" style="--score:${c.progress}"><strong>${c.progress}%</strong><small>Health</small></div></section><nav class="committee-tabs"><button class="active">Overview</button><button>Members</button><button>Responsibilities</button><button>Projects</button><button>Meetings</button><button>Documents</button><button>Activity</button></nav><section class="committee-detail-grid"><article class="glass-card committee-panel"><div class="panel-title"><div><span>Leadership</span><h2>Members</h2></div><button type="button" data-add-member="${c.id}">Add</button></div>${c.members.length?c.members.map(m=>`<div class="member-row"><span>${initials(m.name)}</span><div><strong>${esc(m.name)}</strong><small>${esc(m.role)}</small></div></div>`).join(""):'<div class="dashboard-empty">No members configured.</div>'}</article><article class="glass-card committee-panel"><div class="panel-title"><div><span>Current Work</span><h2>Tasks</h2></div><button type="button" data-add-task="${c.id}">Add</button></div>${c.tasks.length?c.tasks.map(t=>`<div class="task-row"><span class="task-state ${t.status}"></span><div><strong>${esc(t.title)}</strong><small>${t.due||"No due date"}</small></div><b>${t.status.replaceAll("-"," ")}</b></div>`).join(""):'<div class="dashboard-empty">No tasks yet.</div>'}</article><article class="glass-card committee-panel"><div class="panel-title"><div><span>Initiatives</span><h2>Projects</h2></div><button type="button" data-add-project="${c.id}">Add</button></div>${c.projects.length?c.projects.map(p=>`<div class="project-row"><div><strong>${esc(p.name)}</strong><small>${p.status}</small></div><div class="committee-progress"><span style="width:${p.progress}%"></span></div><b>${p.progress}%</b></div>`).join(""):'<div class="dashboard-empty">No projects yet.</div>'}</article><article class="glass-card committee-panel"><div class="panel-title"><div><span>Schedule</span><h2>Next Meeting</h2></div></div><div class="meeting-feature"><strong>${c.nextMeeting||"Not scheduled"}</strong><small>${c.nextMeeting?new Date(c.nextMeeting+"T12:00:00").toLocaleDateString("en-CA",{weekday:"long",month:"long",day:"numeric"}):"Schedule the committee's next meeting."}</small><button class="btn secondary" type="button">Schedule Meeting</button></div></article></section>`,"committees");}
 document.addEventListener("click",e=>{const open=e.target.closest("[data-open-committee]");if(open)return router.go("committee",{id:open.dataset.openCommittee});if(e.target.closest("[data-new-committee]")){const name=prompt("Committee name");if(!name)return;const items=get();items.push({id:`committee-${Date.now()}`,name,purpose:"Committee purpose not yet entered.",chair:"Unassigned",status:"setup",progress:0,nextMeeting:"",members:[],tasks:[],projects:[]});save(items);toast("Committee created.");list();return;}const addMember=e.target.closest("[data-add-member]");if(addMember){const name=prompt("Member name");if(!name)return;const role=prompt("Role","Member")||"Member";const items=get(),c=items.find(x=>x.id===addMember.dataset.addMember);c.members.push({name,role});save(items);toast("Member added.");detail(c.id);return;}const addTask=e.target.closest("[data-add-task]");if(addTask){const title=prompt("Task title");if(!title)return;const items=get(),c=items.find(x=>x.id===addTask.dataset.addTask);c.tasks.push({title,status:"not-started",due:""});save(items);toast("Task added.");detail(c.id);return;}const addProject=e.target.closest("[data-add-project]");if(addProject){const name=prompt("Project name");if(!name)return;const items=get(),c=items.find(x=>x.id===addProject.dataset.addProject);c.projects.push({name,progress:0,status:"active"});save(items);toast("Project added.");detail(c.id);}});
}
function label(s){return s==="on-track"?"On Track":s==="attention"?"Attention Required":"Setup Required"}function initials(v){return v.split(/\s+/).map(x=>x[0]).slice(0,2).join("").toUpperCase()}function esc(v){return String(v||"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));}
