const CATALOG = {
  governance:{defaultSize:"large"},reviews:{defaultSize:"small"},actions:{defaultSize:"small"},amendments:{defaultSize:"small"},annual:{defaultSize:"small"},quick:{defaultSize:"wide"},priorities:{defaultSize:"medium"},committees:{defaultSize:"medium"},meetings:{defaultSize:"wide"},reports:{defaultSize:"medium"},activity:{defaultSize:"medium"},documents:{defaultSize:"wide"},compliance:{defaultSize:"medium"},legal:{defaultSize:"medium"},calendar:{defaultSize:"wide"},notifications:{defaultSize:"medium"},assets:{defaultSize:"medium"},operations:{defaultSize:"medium"},strategy:{defaultSize:"medium"},development:{defaultSize:"wide"},finance:{defaultSize:"medium"},insurance:{defaultSize:"medium"},tenants:{defaultSize:"medium"},fundraising:{defaultSize:"medium"},investments:{defaultSize:"medium"}
};
const CANONICAL={
 "By-Law Committee":[["governance","wide"],["reviews","small"],["actions","small"],["amendments","small"],["compliance","medium"],["legal","medium"],["meetings","wide"],["reports","medium"],["documents","wide"],["activity","medium"]],
 "Finance Committee":[["finance","wide"],["actions","small"],["annual","small"],["meetings","wide"],["reports","medium"],["documents","wide"],["activity","medium"]],
 "Property Committee":[["operations","wide"],["actions","small"],["assets","medium"],["meetings","wide"],["reports","medium"],["calendar","wide"],["documents","wide"],["activity","medium"]],
 "Long-Range Planning Committee":[["strategy","wide"],["actions","small"],["meetings","wide"],["reports","medium"],["calendar","wide"],["documents","wide"],["activity","medium"]],
 "Insurance Committee":[["insurance","wide"],["assets","medium"],["actions","small"],["meetings","wide"],["reports","medium"],["calendar","wide"],["documents","wide"]],
 "Investment Committee":[["investments","wide"],["actions","small"],["meetings","wide"],["reports","medium"],["documents","wide"],["activity","medium"]],
 "Tenant Relations Committee":[["tenants","wide"],["actions","small"],["meetings","wide"],["reports","medium"],["calendar","wide"],["documents","wide"],["activity","medium"]],
 "Fundraising Committee":[["fundraising","wide"],["actions","small"],["meetings","wide"],["reports","medium"],["calendar","wide"],["documents","wide"],["activity","medium"]]
};
export default function register(ctx){
 const {router,state,renderShell,events,storage}=ctx,key="WORKSPACE_CONFIG";
 router.register("dashboard",render);
 function getConfig(){let c=storage.get(key,null)||{name:"By-Law Committee",role:"By-Law Committee",widgets:[]};if(CANONICAL[c.name]){c={...c,widgets:CANONICAL[c.name].map(([id,size],order)=>({id,size,order}))};storage.set(key,c)}return c}
 function metrics(){const m=state.metrics(),a=state.actionSummary(),annual=state.annualTaskSummary(),score=m.total?Math.round(((m.complete+m.discussion*.55+m.amendment*.35)/m.total)*100):0;return{m,a,annual,score,openReviews:Math.max(0,m.total-m.reviewed),amendments:state.amendmentItems(),attention:state.attentionItems().slice(0,4)}}
 function meeting(){return storage.get("MEETING_V1",{title:"Temple Board Meeting",date:"2026-07-29",time:"19:00",sections:[]})}
 function widget(id,d){const {m,a,annual,score,openReviews,amendments,attention}=d,mtg=meeting(),secs=mtg.sections||[],ready=secs.filter(x=>x.ready).length,missing=secs.length-ready;
  if(id==="governance")return `<article class="workspace-widget glass-card governance-card"><div class="governance-copy"><span class="card-kicker">Governance Health</span><strong>${score}%</strong><p>Article review, amendment and evidence readiness.</p><button class="text-action" data-route="review">Open review <b>→</b></button></div><div class="hero-ring" style="--score:${score}"><div><strong>${m.reviewed}</strong><small>of ${m.total}<br>reviewed</small></div></div></article>`;
  if(id==="reviews")return metric(id,"Open Reviews",openReviews,`${m.percent}% complete`,"review");if(id==="actions")return metric(id,"Open Actions",a.open,`${a.overdue} overdue`,"actions");if(id==="amendments")return metric(id,"Amendments",amendments.length,"Tracked workflows","amendments");if(id==="annual")return metric(id,"Annual Tasks",annual.upcoming,"Upcoming obligations","annual");
  if(id==="quick")return actionHub();
  if(id==="meetings")return `<article class="workspace-widget glass-card dashboard-panel meeting-premium"><div class="panel-title"><div><span>Meeting Manager</span><h2>Next Temple Board Meeting</h2></div><button data-route="meetings">Open</button></div><div class="meeting-premium-grid"><div><strong>${esc(mtg.title)}</strong><small>${esc(mtg.date)} · ${esc(mtg.time)}</small><div class="readiness-meter"><i style="--ready:${secs.length?Math.round(ready/secs.length*100):0}%"></i></div><div class="readiness-row"><span class="good">${ready} reports ready</span><span class="warn">${missing} missing</span></div></div><button class="agenda-cta" data-route="meetings"><b>Build agenda</b><small>Pull completed committee reports into the meeting</small><span>→</span></button></div></article>`;
  if(id==="reports")return `<article class="workspace-widget glass-card dashboard-panel"><div class="panel-title"><div><span>Monthly Preparation</span><h2>Committee Reports</h2></div><button data-route="meetings">Open</button></div><div class="prep-mini">${secs.slice(0,4).map(s=>`<div><span class="status-dot ${s.ready?'ok':'due'}"></span><b>${esc(s.committee||s.title)}</b><small>${s.ready?'Submitted':'Required'}</small></div>`).join('')||'<p>No meeting workflow seeded yet.</p>'}</div></article>`;
  if(id==="compliance")return panel("ONCA Review","Compliance Blueprint","15 findings linked to articles, wording, evidence and approval workflows.","compliance");
  if(id==="legal")return panel("Final Safeguard","Legal Review","Prepare the consolidated package for Ontario not-for-profit counsel review.","compliance");
  if(id==="documents")return panel("Document Control","Current Edition","Approved text, certification, amendment history and evidence archive.","export");
  if(id==="activity")return panel("Records","Recent Activity","Review updates, committee submissions and meeting preparation history.","actions");
  if(id==="committees")return panel("Committee Manager","Committee Workspace","Roles, mandates, reports and assigned preparation work.","committees");
  if(id==="priorities")return `<article class="workspace-widget glass-card dashboard-panel"><div class="panel-title"><div><span>Attention Required</span><h2>Today's Priorities</h2></div></div><div class="priority-list">${attention.map(x=>`<button class="priority-item" data-open-direct="${x.articleIndex}:${x.sectionIndex}"><span class="priority-dot ${x.review.status}"></span><span><strong>Section ${x.section.number}</strong><small>${esc(x.section.title)}</small></span><b>Review</b></button>`).join('')||'<div class="dashboard-empty">No urgent items.</div>'}</div></article>`;
  const defs={finance:["Finance Committee","Finance Readiness","Budget, statements, invoices and public-accountant decisions.","committees"],operations:["Property Committee","Building Operations","Inspections, maintenance, safety, keys, alarms and contractors.","committees"],assets:["Property & Insurance","Inventory & Assets","Asset register, condition, valuation and insurance evidence.","committees"],strategy:["Long-Range Planning","Five-Year Plan","Capital projects, milestones, risks and annual plan review.","committees"],insurance:["Insurance Committee","Coverage Readiness","Policies, renewals, quotes, claims and asset values.","committees"],investments:["Investment Committee","Portfolio Oversight","Holdings, performance, recommendations and approvals.","committees"],tenants:["Tenant Relations","Lease & Usage","Renewals, assessments, building use and tenant issues.","committees"],fundraising:["Fundraising Committee","Campaign Readiness","Targets, income, expenses, approvals and reports.","committees"],calendar:["Governance Calendar","Upcoming Deadlines","Meetings, filings, renewals and assigned due dates.","annual"],notifications:["Notifications","Assignments & Alerts","Overdue work, reminders and escalations.","actions"],development:["Administration","CORE Mission Control","Build status, roadmap and system checks.","developer"]};
  if(defs[id])return panel(...defs[id]);return ''
 }
 function actionHub(){return `<article class="workspace-widget glass-card premium-action-hub"><div class="action-hub-head"><div><span>Command Centre</span><h2>Continue the work</h2><p>Focused actions for governance preparation.</p></div><div class="action-hub-mark">✦</div></div><div class="action-hub-primary"><button data-route="review"><i>01</i><span><b>Continue Article Review</b><small>Open marked sections and findings</small></span><em>→</em></button><button data-route="meetings"><i>02</i><span><b>Prepare Board Meeting</b><small>Collect committee reports and build agenda</small></span><em>→</em></button></div><div class="action-hub-secondary"><button data-route="compliance">ONCA Findings</button><button data-route="amendments">Draft Amendments</button><button data-route="actions">Assigned Work</button><button data-route="export">Evidence & Export</button></div></article>`}
 function panel(k,t,p,r){return `<article class="workspace-widget glass-card dashboard-panel"><div class="panel-title"><div><span>${k}</span><h2>${t}</h2></div><button data-route="${r}">Open</button></div><p class="panel-copy">${p}</p><button class="text-action" data-route="${r}">Continue <b>→</b></button></article>`}
 function metric(id,l,v,s,r){return `<button class="workspace-widget glass-card metric-card" data-route="${r}"><span>${l}</span><strong>${v}</strong><small>${s}</small></button>`}
 function render(){const c=getConfig(),d=metrics(),cards=c.widgets.sort((a,b)=>a.order-b.order).map(x=>`<div class="workspace-slot size-${x.size||CATALOG[x.id]?.defaultSize||'medium'}">${widget(x.id,d)}</div>`).join('');renderShell(`<section class="hero cinematic-hero dashboard-intro"><div class="eyebrow">${esc(c.name)} · Temple Board Governance Centre</div><h1>Good ${state.greeting()}, Ryan.</h1><p>Your committee work, meeting preparation and evidence in one place.</p></section><section class="live-workspace premium-grid">${cards}</section>`,`dashboard`)}
 document.addEventListener('click',e=>{const d=e.target.closest('[data-open-direct]');if(d){const[a,b]=d.dataset.openDirect.split(':').map(Number);events.emit('review:open-direct',{articleIndex:a,sectionIndex:b})}})
}
function esc(v){return String(v||'').replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
