const OUTCOMES=["Approved","Defeated","Tabled","Referred","No decision required"];
const PREP=[
 ["Finance Committee","Financial report, budget status, invoices requiring approval and audit/review matters"],
 ["Property Committee","Inspections, maintenance, fire safety, keys/alarm, inventory, stair-chair and contractor updates"],
 ["By-Law Committee","Article reviews, amendments, ONCA findings, approval and legal-review status"],
 ["Long-Range Planning Committee","Five-year plan, capital projects, milestones and decisions required"],
 ["Insurance Committee","Policies, renewals, coverage gaps, quotes, claims and asset valuations"],
 ["Investment Committee","Holdings, performance, recommendations and approvals required"],
 ["Tenant Relations Committee","Leases, renewals, assessments, usage and tenant issues"],
 ["Fundraising Committee","Campaign progress, income, expenses, targets and proposed initiatives"]
];
export default function register(ctx){const{router,renderShell,storage,toast,state}=ctx,key="MEETING_V1";
 function due(date){const d=new Date(date+'T12:00:00');d.setDate(d.getDate()-5);return d.toISOString().slice(0,10)}
 function seedActions(m){const items=state.actionItems();let changed=false;for(const s of m.sections){const marker=`MEET-${m.date}-${s.committee}`;if(!items.some(x=>x.sourceReference===marker)){items.unshift({id:state.nextActionId(),title:`Prepare ${s.committee} report`,description:s.required,sourceType:"Meeting Preparation",sourceReference:marker,assignedCommittee:s.committee,assignedOfficer:"",priority:"high",status:"open",dueDate:s.dueDate,createdDate:new Date().toISOString().slice(0,10),completedDate:"",history:[{date:new Date().toISOString(),event:"Recurring meeting task created",note:`Required for ${m.title} on ${m.date}`} ]});changed=true}}if(changed)state.saveActionItems(items)}
 function get(){let m=storage.get(key,null);if(!m||!m.workflowVersion){m={title:"Temple Board Meeting",date:"2026-07-29",time:"19:00",location:"55 Bridge Street / Google Meet",status:"draft",workflowVersion:2,sections:PREP.map(([committee,required],i)=>({id:`prep-${i+1}`,title:`${committee} Report`,committee,required,dueDate:due("2026-07-29"),ready:false,report:"",evidence:"",notes:"",motion:"",movedBy:"",secondedBy:"",decision:"",complete:false,followUp:{enabled:false,owner:"",committee:"",due:"",priority:"normal",required:"",response:"",documents:""}}))};storage.set(key,m)}seedActions(m);return m}
 const save=m=>storage.set(key,m);router.register("meetings",renderBuilder);router.register("meeting-live",()=>renderLive(0));
 function renderBuilder(){const m=get(),ready=m.sections.filter(x=>x.ready).length;renderShell(`<div class="backline"><button data-route="dashboard">‹ Dashboard</button></div><section class="hero compact-hero"><div class="eyebrow">Monthly Meeting Preparation</div><h1>${m.title}</h1><p>${m.date} · ${m.time} · ${m.location}</p><div class="workspace-toolbar"><button class="btn" data-route="meeting-live">Start Live Meeting</button><button class="btn secondary" data-build-agenda>Build Agenda from Reports</button></div></section><section class="meeting-summary"><article class="glass-card"><span>Reports ready</span><strong>${ready}</strong></article><article class="glass-card"><span>Still required</span><strong>${m.sections.length-ready}</strong></article><article class="glass-card"><span>Agenda sections</span><strong>${m.sections.length}</strong></article></section><section class="agenda-builder"><div class="section-heading"><div><span>Assigned before the meeting</span><h2>Committee Readiness</h2></div><small>Due ${due(m.date)}</small></div>${m.sections.map((s,i)=>`<article class="glass-card agenda-row committee-prep-row"><div class="agenda-order">${i+1}</div><div><strong>${s.committee}</strong><small>${s.required}</small><em>${s.report||'No report filed'}</em></div><span class="agenda-status ${s.ready?'ready':'missing'}">${s.ready?'Ready':'Required'}</span><button data-file-report="${s.id}">${s.ready?'Edit report':'File report'}</button></article>`).join('')}</section>`,`meetings`)}
 function renderLive(index){const m=get(),s=m.sections[index]||m.sections[0],f=s.followUp||{},progress=Math.round(((index+1)/m.sections.length)*100);renderShell(`<section class="live-meeting"><header class="live-top"><button data-live-index="${Math.max(0,index-1)}">‹ Previous</button><span>Item ${index+1} of ${m.sections.length} · ${progress}%</span><button data-live-index="${Math.min(m.sections.length-1,index+1)}">Next ›</button></header><div class="live-layout"><article class="glass-card live-stage"><span class="eyebrow">${s.committee}</span><h1>${s.title}</h1><p>${s.report||'Committee report has not been filed.'}</p><div class="live-fields"><label>Discussion notes<textarea id="live-notes">${s.notes||''}</textarea></label><label>Motion<textarea id="live-motion">${s.motion||''}</textarea></label><div class="two-col"><label>Moved by<input id="live-moved" value="${s.movedBy||''}"></label><label>Seconded by<input id="live-seconded" value="${s.secondedBy||''}"></label></div><label>Outcome<select id="live-decision"><option value="">Select outcome</option>${OUTCOMES.map(v=>`<option ${s.decision===v?'selected':''}>${v}</option>`).join('')}</select></label></div><div class="live-actions"><button class="btn secondary" data-save-live="${index}">Save Draft</button><button class="btn" data-complete-next="${index}">Complete & Next →</button></div></article><aside class="glass-card followup-panel"><div class="panel-title"><div><span>Accountability</span><h2>Follow-up / Action</h2></div></div><label class="follow-check"><input type="checkbox" id="follow-enabled" ${f.enabled?'checked':''}> Create follow-up action</label><div class="follow-fields"><label>Assign to<input id="follow-owner" value="${f.owner||''}"></label><label>Committee<input id="follow-committee" value="${f.committee||s.committee}"></label><div class="two-col"><label>Due date<input type="date" id="follow-due" value="${f.due||''}"></label><label>Priority<select id="follow-priority"><option>normal</option><option>high</option><option>urgent</option></select></label></div><label>Required response<textarea id="follow-required">${f.required||''}</textarea></label><label>Answer / resolution<textarea id="follow-response">${f.response||''}</textarea></label><label>Documents / evidence<textarea id="follow-documents">${f.documents||''}</textarea></label></div></aside></div></section>`,`meetings`)}
 document.addEventListener('click',e=>{const file=e.target.closest('[data-file-report]');if(file){const m=get(),s=m.sections.find(x=>x.id===file.dataset.fileReport),report=prompt(`Committee report for ${s.committee}`,s.report||'');if(report!==null){s.report=report.trim();s.ready=!!s.report;save(m);const items=state.actionItems(),a=items.find(x=>x.sourceReference===`MEET-${m.date}-${s.committee}`);if(a){a.status=s.ready?'completed':'open';a.completedDate=s.ready?new Date().toISOString().slice(0,10):'';state.saveActionItems(items)}renderBuilder();toast('Committee report saved and agenda readiness updated.')}return}if(e.target.closest('[data-build-agenda]')){const m=get();toast(`${m.sections.filter(x=>x.ready).length} committee reports pulled into the agenda.`);return}const nav=e.target.closest('[data-live-index]');if(nav){renderLive(Number(nav.dataset.liveIndex));return}})
}
