const DEFAULT_SECTIONS=[
 "Additions to Agenda","Attendance & Regrets","Approval of Previous Minutes","Correspondence","Treasurer's Report","President","Vice President","Tenant Relations","By-Law Committee","Insurance","Property Committee","Monthly Inspections","Key and Alarm","Inventory & Insurable Assets","Building Accessibility Inspection","Strategic / Long Range Plan","Old Business","New Business","Calendar Review","Adjournment"
];
const OUTCOMES=["Noted","Approved","Defeated","Deferred","Tabled","Withdrawn","Follow-up Required","Awaiting Documents","Return Next Meeting"];
export default function register(ctx){
 const {router,renderShell,storage,toast}=ctx; const key='MEETING_MANAGER';
 const get=()=>storage.get(key,{title:'Temple Board Meeting',date:'2026-07-29',time:'19:00',location:'55 Bridge Street / Google Meet',status:'draft',sections:DEFAULT_SECTIONS.map((title,index)=>({id:`agenda-${index+1}`,title,ready:index<5,report:'',notes:'',motion:'',movedBy:'',secondedBy:'',decision:'',complete:false,followUp:{enabled:false,owner:'',committee:'',due:'',priority:'normal',required:'',response:'',documents:''}}))});
 const save=v=>storage.set(key,v);
 router.register('meetings',()=>renderBuilder());router.register('meeting-live',params=>renderLive(Number(params.index)||0));
 function renderBuilder(){const m=get();renderShell(`<div class="backline"><button type="button" data-route="dashboard">‹ Dashboard</button></div><section class="hero compact-hero"><div class="eyebrow">Meeting Lifecycle · Draft</div><h1>${m.title}</h1><p>${m.date} · ${m.time} · ${m.location}</p><div class="workspace-toolbar"><button class="btn" type="button" data-route="meeting-live">Start Live Meeting</button><button class="btn secondary" type="button" data-add-agenda-item>+ Agenda Item</button></div></section><section class="meeting-summary"><article class="glass-card"><span>Ready</span><strong>${m.sections.filter(x=>x.ready).length}</strong></article><article class="glass-card"><span>Missing reports</span><strong>${m.sections.filter(x=>!x.ready).length}</strong></article><article class="glass-card"><span>Agenda items</span><strong>${m.sections.length}</strong></article></section><section class="agenda-builder"><div class="section-heading"><div><span>Before the meeting</span><h2>Agenda & Committee Readiness</h2></div><small>Committees file their work here</small></div>${m.sections.map((s,i)=>`<article class="glass-card agenda-row"><div class="agenda-order">${i+1}</div><div><strong>${s.title}</strong><small>${s.report||'No report filed'}</small></div><span class="agenda-status ${s.ready?'ready':'missing'}">${s.ready?'Ready':'Missing'}</span><button type="button" data-file-report="${s.id}">File / Edit</button></article>`).join('')}</section>`,`meetings`)}
 function renderLive(index){const m=get(),s=m.sections[index]||m.sections[0],f=s.followUp||{},progress=Math.round(((index+1)/m.sections.length)*100);renderShell(`<section class="live-meeting" data-live-root data-live-index="${index}"><header class="live-top"><button type="button" data-live-index="${Math.max(0,index-1)}">‹ Previous</button><span>Item ${index+1} of ${m.sections.length} · ${progress}%</span><button type="button" data-live-index="${Math.min(m.sections.length-1,index+1)}">Next ›</button></header><div class="live-layout"><article class="glass-card live-stage"><span class="eyebrow">Current agenda item</span><h1>${s.title}</h1><p>${s.report||'Committee report has not been filed.'}</p><div class="live-fields"><label>Discussion notes<textarea id="live-notes">${s.notes||''}</textarea></label><label>Motion (if applicable)<textarea id="live-motion">${s.motion||''}</textarea></label><div class="two-col"><label>Moved by<input id="live-moved" value="${s.movedBy||''}"></label><label>Seconded by<input id="live-seconded" value="${s.secondedBy||''}"></label></div><label>Outcome<select id="live-decision"><option value="">Select outcome</option>${OUTCOMES.map(v=>`<option ${s.decision===v?'selected':''}>${v}</option>`).join('')}</select></label></div><div class="live-actions"><button class="btn secondary" type="button" data-save-live="${index}">Save Draft</button><button class="btn" type="button" data-complete-next="${index}">Complete & Next →</button></div></article><aside class="glass-card followup-panel"><div class="panel-title"><div><span>Accountability</span><h2>Follow-up / Action</h2></div></div><label class="follow-check"><input type="checkbox" id="follow-enabled" ${f.enabled?'checked':''}> Create follow-up action</label><div class="follow-fields"><label>Assign to<input id="follow-owner" value="${f.owner||''}"></label><label>Committee<input id="follow-committee" value="${f.committee||''}"></label><div class="two-col"><label>Due date<input type="date" id="follow-due" value="${f.due||''}"></label><label>Priority<select id="follow-priority"><option ${f.priority==='normal'?'selected':''}>normal</option><option ${f.priority==='high'?'selected':''}>high</option><option ${f.priority==='urgent'?'selected':''}>urgent</option></select></label></div><label>Required response<textarea id="follow-required">${f.required||''}</textarea></label><label>Answer / resolution<textarea id="follow-response">${f.response||''}</textarea></label><label>Documents / evidence<textarea id="follow-documents">${f.documents||''}</textarea></label></div></aside></div></section>`,`meetings`)}
 function capture(index){const m=get(),s=m.sections[index];if(!s)return m;s.notes=q('#live-notes');s.motion=q('#live-motion');s.movedBy=q('#live-moved');s.secondedBy=q('#live-seconded');s.decision=q('#live-decision');s.followUp={enabled:document.querySelector('#follow-enabled')?.checked||false,owner:q('#follow-owner'),committee:q('#follow-committee'),due:q('#follow-due'),priority:q('#follow-priority')||'normal',required:q('#follow-required'),response:q('#follow-response'),documents:q('#follow-documents')};save(m);return m}
 function q(sel){return document.querySelector(sel)?.value||''}
 let autosaveTimer;
 document.addEventListener('input',e=>{if(!e.target.closest('[data-live-root]'))return;clearTimeout(autosaveTimer);autosaveTimer=setTimeout(()=>{const root=document.querySelector('[data-live-root]');if(root)capture(Number(root.dataset.liveIndex));},500)});
 document.addEventListener('change',e=>{if(!e.target.closest('[data-live-root]'))return;const root=document.querySelector('[data-live-root]');if(root)capture(Number(root.dataset.liveIndex));});
 document.addEventListener('click',e=>{
  const live=e.target.closest('[data-live-index]');if(live){e.preventDefault();renderLive(Number(live.dataset.liveIndex));return}
  const file=e.target.closest('[data-file-report]');if(file){const m=get(),s=m.sections.find(x=>x.id===file.dataset.fileReport);const report=prompt(`Report for ${s.title}`,s.report||'');if(report!==null){s.report=report.trim();s.ready=Boolean(s.report);save(m);renderBuilder();toast('Committee report saved.')}return}
  if(e.target.closest('[data-add-agenda-item]')){const title=prompt('Agenda item title');if(title){const m=get();m.sections.push({id:`agenda-${Date.now()}`,title,ready:false,report:'',notes:'',motion:'',movedBy:'',secondedBy:'',decision:'',complete:false,followUp:{}});save(m);renderBuilder()}return}
  const saveBtn=e.target.closest('[data-save-live],[data-complete-next]');if(saveBtn){e.preventDefault();const index=Number(saveBtn.dataset.saveLive??saveBtn.dataset.completeNext),m=capture(index),s=m.sections[index];if(saveBtn.hasAttribute('data-complete-next'))s.complete=true;save(m);toast(s.complete?'Item completed.':'Draft saved.');if(s.complete)renderLive(Math.min(m.sections.length-1,index+1));}
 });
}
