const DEFAULT_SECTIONS=[
 "Additions to Agenda","Attendance & Regrets","Approval of Previous Minutes","Correspondence","Treasurer's Report","President","Vice President","Tenant Relations","By-Law Committee","Insurance","Property Committee","Monthly Inspections","Key and Alarm","Inventory","Stair Chair","Long Range Plan","Old Business","New Business","Calendar Review","Adjournment"
];
export default function register(ctx){
 const {router,renderShell,storage,toast}=ctx; const key='MEETING_MANAGER';
 const get=()=>storage.get(key,{title:'Temple Board Meeting',date:'2026-07-29',time:'19:00',location:'55 Bridge Street / Google Meet',status:'draft',sections:DEFAULT_SECTIONS.map((title,index)=>({id:`agenda-${index+1}`,title,ready:index<5,report:'',notes:'',motion:'',movedBy:'',secondedBy:'',decision:'',complete:false}))});
 const save=v=>storage.set(key,v);
 router.register('meetings',()=>renderBuilder());router.register('meeting-live',()=>renderLive(0));
 function renderBuilder(){const m=get();renderShell(`<div class="backline"><button data-route="dashboard">‹ Dashboard</button></div><section class="hero compact-hero"><div class="eyebrow">Meeting Manager · Test Build</div><h1>${m.title}</h1><p>${m.date} · ${m.time} · ${m.location}</p><div class="workspace-toolbar"><button class="btn" data-route="meeting-live">Start Live Meeting</button><button class="btn secondary" type="button" data-add-agenda-item>+ Agenda Item</button></div></section><section class="meeting-summary"><article class="glass-card"><span>Ready</span><strong>${m.sections.filter(x=>x.ready).length}</strong></article><article class="glass-card"><span>Missing reports</span><strong>${m.sections.filter(x=>!x.ready).length}</strong></article><article class="glass-card"><span>Agenda items</span><strong>${m.sections.length}</strong></article></section><section class="agenda-builder"><div class="section-heading"><div><span>Before the meeting</span><h2>Agenda & Committee Readiness</h2></div><small>Committees file their work here</small></div>${m.sections.map((s,i)=>`<article class="glass-card agenda-row" data-agenda-id="${s.id}"><div class="agenda-order">${i+1}</div><div><strong>${s.title}</strong><small>${s.report||'No report filed'}</small></div><span class="agenda-status ${s.ready?'ready':'missing'}">${s.ready?'Ready':'Missing'}</span><button type="button" data-file-report="${s.id}">File / Edit</button></article>`).join('')}</section>`,`meetings`)}
 function renderLive(index){const m=get(),s=m.sections[index]||m.sections[0],progress=Math.round(((index+1)/m.sections.length)*100);renderShell(`<section class="live-meeting"><div class="live-top"><button data-live-index="${Math.max(0,index-1)}">‹ Previous</button><span>Agenda ${index+1} of ${m.sections.length} · ${progress}%</span><button data-live-index="${Math.min(m.sections.length-1,index+1)}">Next ›</button></div><article class="glass-card live-stage"><span class="eyebrow">Current agenda item</span><h1>${s.title}</h1><p>${s.report||'Committee report has not been filed.'}</p><div class="live-fields"><label>Discussion notes<textarea id="live-notes">${s.notes||''}</textarea></label><label>Motion<textarea id="live-motion">${s.motion||''}</textarea></label><div class="two-col"><label>Moved by<input id="live-moved" value="${s.movedBy||''}"></label><label>Seconded by<input id="live-seconded" value="${s.secondedBy||''}"></label></div><label>Decision<select id="live-decision"><option value="">Select outcome</option>${['Noted','Approved','Defeated','Deferred','Tabled','Withdrawn','Action Required'].map(v=>`<option ${s.decision===v?'selected':''}>${v}</option>`).join('')}</select></label></div><div class="live-actions"><button class="btn secondary" type="button" data-save-live="${index}">Save Item</button><button class="btn" type="button" data-complete-next="${index}">Complete & Next →</button></div></article></section>`,`meetings`)}
 document.addEventListener('click',e=>{
  const live=e.target.closest('[data-live-index]');if(live){renderLive(Number(live.dataset.liveIndex));return}
  const file=e.target.closest('[data-file-report]');if(file){const m=get(),s=m.sections.find(x=>x.id===file.dataset.fileReport);const report=prompt(`Report for ${s.title}`,s.report||'');if(report!==null){s.report=report.trim();s.ready=Boolean(s.report);save(m);renderBuilder();toast('Committee report saved.')}return}
  if(e.target.closest('[data-add-agenda-item]')){const title=prompt('Agenda item title');if(title){const m=get();m.sections.push({id:`agenda-${Date.now()}`,title,ready:false,report:'',notes:'',motion:'',movedBy:'',secondedBy:'',decision:'',complete:false});save(m);renderBuilder()}return}
  const saveBtn=e.target.closest('[data-save-live],[data-complete-next]');if(saveBtn){const index=Number(saveBtn.dataset.saveLive??saveBtn.dataset.completeNext),m=get(),s=m.sections[index];s.notes=document.querySelector('#live-notes')?.value||'';s.motion=document.querySelector('#live-motion')?.value||'';s.movedBy=document.querySelector('#live-moved')?.value||'';s.secondedBy=document.querySelector('#live-seconded')?.value||'';s.decision=document.querySelector('#live-decision')?.value||'';if(saveBtn.hasAttribute('data-complete-next'))s.complete=true;save(m);toast(s.complete?'Item completed.':'Item saved.');renderLive(Math.min(m.sections.length-1,index+(s.complete?1:0)));}
 });
}
